# Generated by Django 3.0.4 on 2020-04-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200416_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panels',
            old_name='type',
            new_name='name',
        ),
    ]
