# Generated by Django 3.0.4 on 2020-04-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200416_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panels',
            name='name',
        ),
        migrations.AddField(
            model_name='panels',
            name='type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.services'),
            preserve_default=False,
        ),
    ]
