# Generated by Django 3.0.4 on 2020-04-15 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200416_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.services'),
        ),
    ]
