# Generated by Django 3.0.4 on 2020-04-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200416_0403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='panels',
            new_name='svcItems',
        ),
    ]
